LakeTrust/Models/Pages/Blog/BlogContainerPage.cs
using EPiServer.Core;
using EPiServer.DataAbstraction;
using System.ComponentModel.DataAnnotations;

namespace LakeTrust.Models.Pages
{
    [BlogContentType(DisplayName = "Blog Container", GroupName = Global.GroupNames.Blog, AvailableInEditMode = false, GUID = "9d8a24f9-5f24-461d-88af-e27f8c6c3b50", Description = "Represents the year and month container for posts.")]
    [SiteImageUrl]
    public class BlogContainerPage : LakeTrustBaseModel
    {
        [Display(Name = "Page Title", Order = 10, Description = "The Title for the page.", GroupName = SystemTabNames.Content)]
        [Required(ErrorMessage = "You must enter a title")]
        public virtual string Title { get; set; }

        [Display(Name = "Left Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 70)]
        public virtual ContentArea LeftBlockArea { get; set; }

        [Display(Name = "Right Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 80)]
        public virtual ContentArea RightBlockArea { get; set; }

        [Display(Name = "Right Fixed Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 90)]
        public virtual ContentArea RightFixedBlockArea { get; set; }

        [Display(Name = "Top Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 100)]
        public virtual ContentArea TopBlockArea { get; set; }

        [Display(Name = "Bottom Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 110)]
        public virtual ContentArea BottomBlockArea { get; set; }
    }
}

LakeTrust/Models/Pages/Blog/BlogPage.cs
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace LakeTrust.Models.Pages
{
    [BlogContentType(DisplayName = "Blog", GroupName = Global.GroupNames.Blog, GUID = "acd7bce7-a849-493f-a2d7-10676825fea3", Description = "")]
    [AvailableContentTypes(Include = new[] { typeof(BlogPostPage), typeof(BlogContainerPage) }, IncludeOn = new[] { typeof(StandardPage) })]
    [SiteImageUrl]
    public class BlogPage : LakeTrustBaseModel
    {
        public override void SetDefaultValues(ContentType contentType)
        {
            base.SetDefaultValues(contentType);
            this.PostPerPage = 10;
            this.PopularPostCount = 3;
        }

        [Display(Name = "Page Title", Order = 10, Description = "The Title for the page.", GroupName = SystemTabNames.Content)]
        [Required(ErrorMessage = "You must enter a title")]
        public virtual string Title { get; set; }

        [Display(Name = "Posts Per Page", Order = 15, GroupName = SystemTabNames.Content)]
        public virtual int PostPerPage { get; set; }

        [Display(Name = "Popular Posts Count", Order = 16, GroupName = SystemTabNames.Content)]
        public virtual int PopularPostCount { get; set; }

        [Display(Name = "Left Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 70)]
        public virtual ContentArea LeftBlockArea { get; set; }

        [Display(Name = "Right Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 80)]
        public virtual ContentArea RightBlockArea { get; set; }

        [Display(Name = "Right Fixed Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 90)]
        public virtual ContentArea RightFixedBlockArea { get; set; }

        [Display(Name = "Top Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 100)]
        public virtual ContentArea TopBlockArea { get; set; }

        [Display(Name = "Bottom Block Area", Description = "A content area where you can place blocks", GroupName = Global.GroupNames.Blocks, Order = 110)]
        public virtual ContentArea BottomBlockArea { get; set; }

        [Display(Name = "ExludeFromIndex", Description = "If checked, the documemnt will not be indexed", GroupName = SystemTabNames.Settings, Order = 100)]
        public virtual bool ExcludeFromIndex { get; set; }
    }
}

LakeTrust/Models/Pages/Blog/BlogPostPage.cs
using EPiServer;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.Web;
using LakeTrust.Business;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace LakeTrust.Models.Pages
{
    [BlogContentType(DisplayName = "Blog Post", GroupName = Global.GroupNames.Blog, GUID = "069aa884-2661-422a-9022-fedc65428670", Description = ""),
    SiteImageUrl(Global.StringConstants.StaticGraphicsFolderPath + "page-type-thumbnail-article.png")]
    public class BlogPostPage : SitePageData
    {
        [Display(Name = "Blog Post Listing Thumbnail", Order = 888, Description = "The image for this blog post.", GroupName = SystemTabNames.Content)]
        [UIHint(UIHint.Image)]
        [ScaffoldColumn(true)]
        public virtual Url BlogPostImage { get; set; }

        [Display(Name = "Blog Post Listing Thumbnail Alt Text", Order = 888, Description = "The image for this blog post.", GroupName = SystemTabNames.Content)]
        [ScaffoldColumn(true)]
        public virtual string BlogPostImageAltText { get; set; }

        [Display(Name = "Blog Post Teaser", Order = 9999, Description = "The teaser for the blog post.", GroupName = SystemTabNames.Content)]
        public virtual XhtmlString Teaser { get; set; }

        [Display(Order = 10000, Name = "Blog Content", Description = "The content of the blog will be shown in the main content area of the page, using the XHTML-editor you can insert for example text, images and tables.")]
        public override XhtmlString MainBody { get; set; }

        [Display(Name = "Disable Comments", Order = 8000, Description = "If checked, comments will not be allowed on the blog post.", GroupName = SystemTabNames.Content)]
        public virtual bool CommentsClosed { get; set; }

        public override string SEODescription
        {
            get
            {
                var description = this.GetPropertyValue(x => x.SEODescription);
                if (!string.IsNullOrEmpty(description))
                    return description;
                return this.GetPropertyValue(x => x.Teaser, new XhtmlString()).ToHtmlString().StripTags();
            }
            set
            {
                this.SetPropertyValue(x => x.SEODescription, value);
            }
        }

        [Display(Name = "Import PostId")]
        [Editable(false)]
        [ScaffoldColumn(false)]
        public virtual int ImportPostId { get; set; }

        [Display(Name = "Number of Views")]
        [Editable(false)]
        [ScaffoldColumn(false)]
        public virtual int Views { get; set; }

        [Display(Name = "Blog Post Catgories", Order = 800)]
        [UIHint(LakeTrust.Global.SiteUIHints.Tags)]
        public virtual string Tags { get; set; }
    }
}

LakeTrust/Controllers/Blog/BlogContainerPageController.cs
using EPiServer;
using EPiServer.Framework.DataAnnotations;
using LakeTrust.Business.Services;
using LakeTrust.Models.Pages;
using LakeTrust.Models.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace LakeTrust.Controllers
{
    [TemplateDescriptor(Default = true)]
    public class BlogContainerPageController : PageControllerBase<BlogContainerPage>
    {
        private readonly IContentRepository contentRepository;
        private readonly IContentLoader contentLoader;
        private readonly BlogService blogService;

        public BlogContainerPageController(IContentLoader contentLoader, IContentRepository contentRepository, BlogService blogService)
        {
            this.contentLoader = contentLoader;
            this.contentRepository = contentRepository;
            this.blogService = blogService;
        }

        public virtual ActionResult Index(BlogContainerPage currentPage, int pageIndex = 1, string category = "all")
        {
            var model = new ListingViewModel<BlogContainerPage, BlogPostPage>(currentPage);
            int totalItems = 0;
            model.Pages = blogService.GetBlogPosts(currentPage.ContentLink, out totalItems, category, pageIndex).Cast<BlogPostPage>();

            model.TotalItems = totalItems;
            model.PageIndex = pageIndex;
            model.PageWeight = 10;
            return View(model);
        }

        public virtual ActionResult Paging(BlogContainerPage currentPage, int pageIndex = 1, string category = "all")
        {
            var model = new ListingViewModel<BlogContainerPage, BlogPostPage>(currentPage);
            int totalItems = 0;
            model.Pages = blogService.GetBlogPosts(currentPage.ContentLink, out totalItems, category, pageIndex).Cast<BlogPostPage>();

            model.TotalItems = totalItems;
            model.PageIndex = pageIndex;
            model.PageWeight = 10;
            return View("Index", model);
        }
    }
}

LakeTrust/Controllers/Blog/BlogPageController.cs
using EPiServer;
using EPiServer.Core;
using EPiServer.Framework.DataAnnotations;
using EPiServer.Web;
using LakeTrust.Business.Services;
using LakeTrust.Models.Pages;
using LakeTrust.Models.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace LakeTrust.Controllers
{
    [TemplateDescriptor(Default = true)]
    public class BlogPageController : PageControllerBase<BlogPage>
    {
        private readonly IContentRepository contentRepository;
        private readonly IContentLoader contentLoader;
        private readonly BlogService blogService;
        private readonly TwitterFeedService twitterFeed;
        private readonly SiteDefinition siteDefinition;

        public BlogPageController(IContentLoader contentLoader, IContentRepository contentRepository, BlogService blogService, TwitterFeedService twitterFeed, SiteDefinition siteDefinition)
        {
            this.contentLoader = contentLoader;
            this.contentRepository = contentRepository;
            this.blogService = blogService;
            this.siteDefinition = siteDefinition;
            this.twitterFeed = twitterFeed;
        }

        public virtual ActionResult Index(BlogPage currentPage)
        {
            int totalItems = 0;
            var pages = this.blogService.GetBlogPosts(currentPage.ContentLink, out totalItems, "all", 1).Cast<BlogPostPage>();
            var model = new ListingViewModel<BlogPage, BlogPostPage>(currentPage)
            {
                TotalItems = totalItems,
                Pages = pages,
                PageIndex = 1,
                PageWeight = 10
            };

            return View(model);
        }

        public virtual ActionResult Paging(BlogPage currentPage, int pageIndex = 1, string searchTerm = "all")
        {
            int totalItems = 0;
            var pages = this.blogService.GetBlogPosts(currentPage.ContentLink, out totalItems, searchTerm, pageIndex).Cast<BlogPostPage>();

            var model = new ListingViewModel<BlogPage, BlogPostPage>(currentPage)
            {
                TotalItems = totalItems,
                Pages = pages,
                PageIndex = pageIndex,
                PageWeight = 10
            };

            return View("Index", model);
        }

        public virtual ActionResult PopularBlogPosts(LakeTrustBaseModel blogPage)
        {
            var page = this.contentLoader.Get<BlogPage>(blogPage.GetPropertyValue<PageReference>(Global.StringConstants.BlogStartReference));
            var posts = this.blogService.GetMostPopularBlogPost(page.ContentLink, blogPage.GetPropertyValue<int>("PopularPostCount", 3)).Cast<BlogPostPage>();
            return PartialView(posts);
        }

        public virtual ActionResult BlogCategories(LakeTrustBaseModel blogPage)
        {
            var page = this.contentLoader.Get<BlogPage>(blogPage.GetPropertyValue<PageReference>(Global.StringConstants.BlogStartReference));
            var categories = this.blogService.BlogCategories(page.ContentLink.ToPageReference());
            return PartialView(categories);
        }

        public virtual ActionResult TwitterFeed()
        {
            var start = this.contentLoader.Get<StartPage>(this.siteDefinition.StartPage);
            var tweets = this.twitterFeed.GetTweets(start.NumberOfTwitterItems, start.TwitterUserName);
            return PartialView(tweets);
        }
    }
}

LakeTrust/Controllers/Blog/BlogPostPageController.cs
using EPiServer;
using EPiServer.Core;
using EPiServer.Framework.DataAnnotations;
using LakeTrust.Models.Pages;
using LakeTrust.Models.ViewModels;
using System.Web.Mvc;

namespace LakeTrust.Controllers
{
    [TemplateDescriptor(Default = true)]
    public class BlogPostPageController : PageControllerBase<BlogPostPage>
    {
        private readonly IContentLoader contentLoader;

        public BlogPostPageController(IContentLoader contentLoader)
        {
            this.contentLoader = contentLoader;
        }

        public virtual ActionResult Index(BlogPostPage currentPage)
        {
            var model = new PageViewModel<BlogPostPage>(currentPage);
            var blogRootPage = this.contentLoader.Get<BlogPage>(currentPage.GetPropertyValue<PageReference>(Global.StringConstants.BlogStartReference));
            if (!User.Identity.IsAuthenticated)
                LakeTrust.Business.Blog.BlogPostView.Increment(currentPage.ContentGuid, blogRootPage.ContentGuid);

            return View(model);
        }
    }
}

LakeTrust/Views/Shared/Layouts/_Blog.cshtml
@model IPageViewModel<LakeTrustBaseModel>
@{
    Layout = "~/Views/Shared/Layouts/_Site.cshtml";
}
@section Header{
    @RenderSection("Header", false)
}
<div class="row">
    <div class="col-xs-12 col-sm-9" id="main-column">
        @RenderBody()
    </div>
    <div class="col-xs-12 col-sm-3" id="right-column">
        @Html.Action("BlogCategories", "BlogPage", new { blogPage = Model.CurrentPage })
        @Html.Action("PopularBlogPosts", "BlogPage", new { blogPage = Model.CurrentPage })
        @Html.Action("TwitterFeed", "BlogPage")
        @RenderSection("RightColumn", false)
    </div>
</div>
@section FooterScripts{
    @RenderSection("FooterScripts", false)
}

LakeTrust/Views/Shared/Layouts/_HQSite.cshtml
@using System.Web.Optimization
@using EPiServer.Framework.Web.Mvc.Html
@using EPiServer.Web.Mvc.Html

<!doctype html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"><![endif]-->
<!--[if IE 7 ]><html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]><html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Lake Trust Credit Union HQ</title>
    @Scripts.Render("~/Scripts/Modernizr")
    @Styles.Render("~/Content/LakeTrustHQ")
    <!--[if lte IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @Html.RequiredClientResources("Header")
</head>
<body>
    @Html.RenderEPiServerQuickNavigator()
    @Html.FullRefreshPropertiesMetaData()
    <div id="LakeTrustHqPage" class="container">
        <div class="row">
            <div class="col-xs-12">
                @RenderBody()
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-9 col-md-offset-3">
                <div id="footer">
                    &copy; Copyright @DateTime.Now.Year. All Rights Reserved.  Lake Trust Credit Union.
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/LakeTrustHQ")
    @RenderSection("FooterScripts", false)
    @Html.RequiredClientResources("Footer")
</body>
</html>

LakeTrust/Views/Shared/Layouts/_Root.cshtml
@model IPageViewModel<LakeTrustBaseModel>
@using System.Web.Optimization
@using EPiServer.Framework.Web.Mvc.Html
@using EPiServer.Web.Mvc.Html
@using EPiServer.Web.Routing
<!doctype html>
<!--[if lt IE 7 ]><html lang="en" class="no-js ie6"><![endif]-->
<!--[if IE 7 ]><html lang="en" class="no-js ie7"><![endif]-->
<!--[if IE 8 ]><html lang="en" class="no-js ie8"><![endif]-->
<!--[if IE 9 ]><html lang="en" class="no-js ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>@Model.CurrentPage.Name - Lake Trust Credit Union</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/Content/images/lake-trust.ico">
    <link rel="apple-touch-icon" href="/Content/images/apple-touch-icon.png">
    @Styles.Render("~/Content/LakeTrust")
    @Scripts.Render("~/Scripts/Modernizr")
    <!--[if lt IE 9]>
        <link rel="stylesheet" href="/Content/ie.css">
        @Scripts.Render("~/Scripts/IE")
    <![endif]-->
    <!--[if IE 6]>
        <style>
            body {behavior: url("csshover3.htc");}
            #menu li .drop {background:url("img/drop.gif") no-repeat right 8px;
        </style>
    <![endif]-->
    @if (Model.PageHeader != null)
    {
        if (Model.PageHeader.HeaderJavascriptIncludes != null)
        {
            foreach (var jsFile in Model.PageHeader.HeaderJavascriptIncludes)
            {
                <script type="text/javascript" src="@UrlResolver.Current.GetUrl(jsFile.Href)"></script>
            }
        }
    }
    @if (Model.Layout.CustomHeaderScripts != null)
    {
        if (!string.IsNullOrWhiteSpace(Model.Layout.CustomHeaderScripts.ToHtmlString()))
        {
            @Html.Raw(Model.Layout.CustomHeaderScripts)
        }
    }
    @RenderSection("Header", false)
    @Html.RequiredClientResources("Header")
</head>
<body class="@Model.Layout.BodyClasses">
    @Html.RenderEPiServerQuickNavigator()
    @Html.FullRefreshPropertiesMetaData()

    @if (!this.Model.Layout.HideScreenReaderLink)
    {
        <a class="sr-only" id="main" href="#pagecontainer" accesskey="1">Skip to main content</a>
    }
    @if (Model.CurrentPage.ContentLink.CompareToIgnoreWorkID(EPiServer.Web.SiteDefinition.Current.StartPage))
    {
        <!--[if lte IE 8]>
            <div class="row">
                <div class="col-xs-12">
                    <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
                </div>
            </div>
        <![endif]-->
    }
    @RenderBody()
    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/LakeTrust")
    @if (Model.PageFooter != null)
    {
        if (Model.PageFooter.JavascriptIncludes != null)
        {
            foreach (var jsFile in Model.PageFooter.JavascriptIncludes)
            {
                <script type="text/javascript" src="@UrlResolver.Current.GetUrl(jsFile.Href)"></script>
            }
        }
    }
    <!--[if lt IE 9]>
        <script type="text/javascript" src="/Scripts/PIE/PIE_IE678.js"></script>
    <![endif]-->
    <!--[if IE 9]>
        <script type="text/javascript" src="/Scripts/PIE/PIE_IE9.js"></script>
    <![endif]-->
    @RenderSection("FooterScripts", false)
    <!--[if lt IE 7 ]>
    <script src="@Url.Content("~/Scripts/libs/dd_belatedpng.js")"></script>
    <script> DD_belatedPNG.fix('img, .png_bg');</script>
    <![endif]-->
    @Html.RequiredClientResources("Footer")
</body>
</html>

LakeTrust/Views/Shared/Layouts/_Site.cshtml
@model IPageViewModel<LakeTrustBaseModel>
@{
    Layout = "~/Views/Shared/Layouts/_Root.cshtml";
}

@RenderSection("Header", false)
@if (!Model.Layout.HideHeader)
{
    @Html.Partial("PageHeader", Model.PageHeader)
}
<div class="container" id="LakeTrustPage">
    @RenderBody()
</div>
@if (!Model.Layout.HideFooter)
{
    @Html.Partial("PageFooter", Model.PageFooter)
}
@RenderSection("FooterScripts", false)

LakeTrust/Views/Shared/Layouts/_TwoColumn.cshtml
@{
    Layout = "~/Views/Shared/Layouts/_Site.cshtml";
}
@section Header{
    @RenderSection("Header", false)
}
<div class="row">
    <div class="col-md-3 hidden-print">
        @RenderSection("LeftColumn", false)
    </div>
    <div class="col-md-9" id="main-column">
        @RenderBody()
    </div>
</div>
@section FooterScripts{
    @RenderSection("FooterScripts", false)
}